name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch: # Manual trigger
jobs: 
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  
        uses: actions/checkout@v4
      - name: Show event name
        run: "echo 'Event name: ${{ github.event_name }}'"
      - name: Show branch name
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Branch: $BRANCH"

      - name: List repository files        
        run: |
          echo "Repository files:"
          ls -R .
