name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch: # Manual trigger
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Output the event name that triggered the workflow
        run: 'echo "Event name: ${{ github.event_name }}"'

      - name: Output the current branch name
        run: |
          echo "Branch: ${GITHUB_REF#refs/heads/}"

      - name: List all files in the repository
        run: ls -R .
